# Generated by Django 5.1.7 on 2025-03-27 16:20

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', django_jsonform.models.fields.JSONField(verbose_name='Ученик')),
                ('answers', django_jsonform.models.fields.JSONField(verbose_name='Ответы')),
            ],
            options={
                'verbose_name': 'Результат квеста',
                'verbose_name_plural': 'Результаты квеста',
            },
        ),
        migrations.AddField(
            model_name='quest',
            name='label',
            field=models.CharField(default='Оп-оп', max_length=64, verbose_name='Ярлык'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quest',
            name='questions',
            field=django_jsonform.models.fields.JSONField(default=[], verbose_name='Вопросы'),
            preserve_default=False,
        ),
    ]
