# Generated by Django 5.1.7 on 2025-03-27 16:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_questresult_quest_label_quest_questions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='questresult',
            options={},
        ),
        migrations.RemoveField(
            model_name='quest',
            name='label',
        ),
        migrations.AddField(
            model_name='questresult',
            name='quest_pk',
            field=models.IntegerField(default=1, verbose_name='Ключ квеста'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questresult',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
