# Generated by Django 5.1.7 on 2025-03-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_alter_quest_options_alter_questresult_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='type',
            field=models.CharField(choices=[('single', 'С выбором одного'), ('multiply', 'С выбором нескольких')], default='single', max_length=16, verbose_name='Тип'),
            preserve_default=False,
        ),
    ]
