# Generated by Django 5.1.7 on 2025-04-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_quest_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quest',
            old_name='questions',
            new_name='tasks',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='type',
        ),
        migrations.AddField(
            model_name='quest',
            name='scene',
            field=models.CharField(choices=[('office', 'Офис'), ('workshop', 'Мастерская')], default='office', max_length=16, verbose_name='Сцена'),
            preserve_default=False,
        ),
    ]
