# Generated by Django 5.1.7 on 2025-04-15 10:33

import django.db.models.deletion
import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0005_rename_questions_quest_tasks_remove_quest_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quest',
            options={'verbose_name': 'Квест', 'verbose_name_plural': 'Квесты'},
        ),
        migrations.AlterModelOptions(
            name='questresult',
            options={'verbose_name': 'Результат квеста', 'verbose_name_plural': 'Результаты квестов'},
        ),
        migrations.RemoveField(
            model_name='questresult',
            name='quest_pk',
        ),
        migrations.AddField(
            model_name='quest',
            name='label',
            field=models.CharField(default='Тестовый', max_length=16, verbose_name='Ярлык'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questresult',
            name='quest',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='interface.quest'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quest',
            name='scene',
            field=models.CharField(choices=[('office', 'Офис'), ('workshop', 'Мастерская')], default='office', max_length=16, verbose_name='Сцена'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='tasks',
            field=django_jsonform.models.fields.JSONField(default=list, verbose_name='Вопросы'),
        ),
        migrations.AlterField(
            model_name='questresult',
            name='answers',
            field=django_jsonform.models.fields.JSONField(default=list, verbose_name='Ответы'),
        ),
        migrations.AlterField(
            model_name='questresult',
            name='student',
            field=django_jsonform.models.fields.JSONField(default=dict, verbose_name='Ученик'),
        ),
    ]
