# Generated by Django 5.1.7 on 2025-04-15 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0006_alter_quest_options_alter_questresult_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questresult',
            name='student',
        ),
        migrations.AddField(
            model_name='questresult',
            name='student_class',
            field=models.CharField(default='8А', max_length=8, verbose_name='Класс студента'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questresult',
            name='student_firstname',
            field=models.CharField(default='Иван', max_length=32, verbose_name='Имя студента'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questresult',
            name='student_lastname',
            field=models.CharField(default='Иванов', max_length=32, verbose_name='Фамилия студента'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questresult',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.quest', verbose_name='Квест'),
        ),
    ]
