# Generated by Django 5.1.7 on 2025-04-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0007_remove_questresult_student_questresult_student_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questresult',
            name='points',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Баллы'),
            preserve_default=False,
        ),
    ]
