# Generated by Django 5.1.7 on 2025-05-01 13:49

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0008_questresult_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='scene',
        ),
        migrations.AddField(
            model_name='quest',
            name='location',
            field=models.CharField(choices=[('office', 'Офис'), ('workshop', 'Мастерская')], default='office', max_length=16, verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='tasks',
            field=django_jsonform.models.fields.JSONField(default=list, verbose_name='Задания'),
        ),
    ]
