# Generated by Django 5.1.7 on 2025-05-04 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0009_remove_quest_scene_quest_location_alter_quest_tasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quest',
            old_name='location',
            new_name='scene',
        ),
    ]
