# Generated by Django 5.2.5 on 2025-08-29 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0010_rename_location_quest_scene'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questresult',
            name='quest',
        ),
        migrations.DeleteModel(
            name='Quest',
        ),
        migrations.DeleteModel(
            name='QuestResult',
        ),
    ]
