# Generated by Django 5.2.5 on 2025-08-29 14:46

import django.db.models.deletion
import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=16, verbose_name='Ярлык')),
                ('scene', models.CharField(choices=[('office', 'Офис'), ('workshop', 'Мастерская')], default='office', max_length=16, verbose_name='Локация')),
                ('tasks', django_jsonform.models.fields.JSONField(default=list, verbose_name='Задания')),
            ],
            options={
                'verbose_name': 'Квест',
                'verbose_name_plural': 'Квесты',
            },
        ),
        migrations.CreateModel(
            name='QuestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_firstname', models.CharField(max_length=32, verbose_name='Имя студента')),
                ('student_lastname', models.CharField(max_length=32, verbose_name='Фамилия студента')),
                ('student_class', models.CharField(max_length=8, verbose_name='Класс студента')),
                ('points', models.PositiveSmallIntegerField(verbose_name='Баллы')),
                ('answers', django_jsonform.models.fields.JSONField(default=list, verbose_name='Ответы')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.quest', verbose_name='Квест')),
            ],
            options={
                'verbose_name': 'Результат квеста',
                'verbose_name_plural': 'Результаты квестов',
            },
        ),
    ]
