# Generated by Django 5.2.5 on 2025-08-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='label',
        ),
        migrations.AddField(
            model_name='quest',
            name='title',
            field=models.CharField(default='Название', max_length=16, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questresult',
            name='student_class',
            field=models.CharField(max_length=3, verbose_name='Класс студента'),
        ),
        migrations.AlterField(
            model_name='questresult',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата прохождения'),
        ),
    ]
