# Generated by Django 5.2.5 on 2025-08-29 18:19

import django.db.models.deletion
import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_remove_quest_label_quest_title_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quest',
            new_name='Test',
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_firstname', models.CharField(max_length=32, verbose_name='Имя студента')),
                ('student_lastname', models.CharField(max_length=32, verbose_name='Фамилия студента')),
                ('student_class', models.CharField(max_length=3, verbose_name='Класс студента')),
                ('points', models.PositiveSmallIntegerField(verbose_name='Баллы')),
                ('answers', django_jsonform.models.fields.JSONField(default=list, verbose_name='Ответы')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата прохождения')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.test', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Результат квеста',
                'verbose_name_plural': 'Результаты квестов',
            },
        ),
        migrations.DeleteModel(
            name='QuestResult',
        ),
    ]
