# Generated by Django 5.2.5 on 2025-08-31 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_rename_quest_test_testresult_delete_questresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.AlterModelOptions(
            name='testresult',
            options={'verbose_name': 'Результат теста', 'verbose_name_plural': 'Результаты тестов'},
        ),
        migrations.AddField(
            model_name='testresult',
            name='student_character',
            field=models.CharField(choices=[('adam', 'Адам'), ('alex', 'Алекс'), ('bob', 'Боб')], default='adam', max_length=16, verbose_name='Персонаж студента'),
            preserve_default=False,
        ),
    ]
