# Generated by Django 5.2.5 on 2025-09-01 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_test_options_alter_testresult_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='student_character',
        ),
    ]
