# Generated by Django 5.2.5 on 2025-09-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_remove_testresult_student_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(max_length=32, verbose_name='Название'),
        ),
    ]
