# Generated by Django 5.2.5 on 2025-09-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_test_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='timer',
            field=models.SmallIntegerField(default=0, verbose_name='Таймер'),
        ),
    ]
