# Generated by Django 5.2.5 on 2025-09-02 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_test_timer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='timer',
        ),
    ]
