# Generated by Django 5.2.5 on 2025-09-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_remove_test_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='timer',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Таймер (секунды)'),
        ),
        migrations.AlterField(
            model_name='test',
            name='scene',
            field=models.CharField(choices=[('office', 'Офис'), ('workshop', 'Мастерская')], default='office', max_length=16, verbose_name='Сцена'),
        ),
    ]
